---
- name: "Check if SBT is already installed"
  ansible.builtin.command: "which sbt"
  failed_when: false
  register: sbt_current
  changed_when: false
  check_mode: false
  tags: sbt

- name: "Configure APT"
  block:
    - name: "Install APT dependencies"
      apt:
        name: "{{ sbt_dependencies }}"
        state: present

    - name: "Add SBT repository"
      lineinfile:
        path: /etc/apt/sources.list.d/sbt.list
        line: "deb https://repo.scala-sbt.org/scalasbt/debian all main"
        create: true
        state: present

    - name: "Add SBT legacy repository"
      lineinfile:
        path: /etc/apt/sources.list.d/sbt_legacy.list
        line: "deb https://repo.scala-sbt.org/scalasbt/debian /"
        create: true
        state: present

    - name: "Import SBT Ubuntu GPG key"
      apt_key:
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823"
        state: present
  when: sbt_current.rc != 0
  tags: sbt

- name: "Install SBT"
  apt:
    name: "{% if sbt_global_version is defined %}sbt={{ sbt_global_version }}{% else %}sbt{% endif %}"
    state: present
  tags: sbt
